import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../app/Navbar/page"
import Footer from "./Footer/page";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-gradient-to-r from-blue-950 to-gray-800"><Navbar /></header>

        {/* Each page can set its own background */}
        <main className="min-h-screen bg-gradient-to-r from-blue-950 to-gray-800">{children}</main>
         <Toaster />
        <footer><Footer /></footer>
      </body>
    </html>
  );
}
